Repository 106-inc/sim2022, pull requests merged in 2022-11, with the labels that each got.

#24 Added license file for riscv spec
  docs/spec/LICENSE
Labels: documentation, Minor

#11 basic arithmetic, mem, branches
  include/common/common.hh
  include/common/state.hh
  include/executor/executor.hh
  include/hart/hart.hh
  src/executor/executor.cc
  src/hart/hart.cc
  test/unit/executor/CMakeLists.txt
  test/unit/executor/M.cc
  test/unit/executor/RV32I.cc
  test/unit/executor/executor_test.hh
Labels: Critical

#22 Added minimum required compiler version check
  CMakeLists.txt
Labels: Minor, infra

#23 Decoder improve
  include/common/common.hh
  src/decoder/CMakeLists.txt
  src/decoder/decoder.py
  test/unit/decoder/decode.cc
Labels: enhancement, Minor
